spring:
  application:
    name: ApiGateway

eureka:
  instance:
   preferIpAddress: true
  client:
       registerWithEureka: true
       fetchRegistry: true
       serviceUrl:
        defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    UserService:
      path: /userservice/*
      serviceId: USERSERVICE    Orderitems:
      path: /orderitem/*
      serviceId: ORDERSERVICE
  
server:
  servlet:
    context-path: /api  