spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
          - localhost:9092
      bindings:
        input:
         binder: kafka
         destination: myTopic
         content-type: application/json
        output:
          binder: kafka
          destination: myTopic
          content-type: application/json
          
eureka:
  instance:
   preferIpAddress: true
  client:
       registerWithEureka: true
       fetchRegistry: true
       serviceUrl:
        defaultZone: http://localhost:8761/eureka/
          
